# Generated by Django 6.0 on 2026-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionnova_app', '0007_order_actual_delivery_date_order_delivery_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
